dist: bionic
language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

matrix:
  include:
    - php: 7.4.7
      name: Static Analysis
      script:
        - composer test:lint
        - composer test:types

before_script:
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist

script:
    - composer test:unit
